-- EPUB building for WikiReader.
-- Wraps KOReader's built-in Wikipedia.createEpub() with HTML cleanup
-- (stripping navboxes, removing image captions, etc.; converting math
-- formulas to readable text; extracting hatnotes into bordered boxes).
-- Infobox tables are stripped by default; the "Show infoboxes"
-- setting keeps them instead, forced to span the full page
-- width like wikitables. Also provides standalone EPUB builders for
-- search results and category navigation pages.

local Archiver = require("ffi/archiver")
local DocSettings = require("docsettings")
local Trapper = require("ui/trapper")
local Wikipedia = require("ui/wikipedia")
local socket_url = require("socket.url")
local util = require("util")
local logger = require("logger")
local _ = require("gettext")

local cache = require("wikireader-cache")
local cladogram = require("cladogram")
local htmlclean = require("htmlclean")
local latex = require("latex")
local qrimage = require("qrimage")
local wutil = require("wikiutil")

local M = {}

--[[-------------------------------------------------------------------------
Full article EPUB builder
--]]

-- Fetches an article and converts it to an EPUB via Wikipedia.createEpub(),
-- after cleaning the HTML: clutter tables (navbox/sidebar/rmbox, and infobox
-- unless "Show infoboxes" is on) and the category list are stripped, math
-- formulas become readable text, cladograms become text diagrams, and
-- leading hatnotes are boxed. With "media as QR codes" (the default) each
-- media box keeps its caption and gets a QR code of its File: page; with it
-- off the boxes are removed entirely. The resolved title and short
-- description are recovered from the API response and written into the EPUB
-- metadata. A kept infobox's media cells are dropped before the QR pass.
function M.buildEpub(epub_path, title, lang, callback)

    local short_description = nil   -- extracted from the HTML
    local resolved_title = nil      -- from the API response

    -- QR-code images: toggled by "wikireader_qr_media"; generated by
    -- qrimage during the HTML pass and stitched in from the Archiver hooks.
    local qr_enabled = G_reader_settings:isTrue("wikireader_qr_media")
    local qr_size = G_reader_settings:readSetting("wikireader_qr_size") or qrimage.DEFAULT_QR_SIZE
    local qr_images = {}

    -- Patch redirects support
    local original_phtml_redirects = Wikipedia.wiki_phtml_params.redirects
    Wikipedia.wiki_phtml_params.redirects = ""

    local original_getFullPageHtml = Wikipedia.getFullPageHtml
    Wikipedia.getFullPageHtml = function(self, wiki_title, wiki_lang)
        local ok, result = pcall(original_getFullPageHtml, self, wiki_title, wiki_lang)
        if not ok or not result then
            return nil
        end
        if result and result.text and result.text["*"] then
            local html = result.text["*"]

            -- Extract short description from the HTML before stripping it.
            local short_desc_pat = '<div[^>]*class="[^"]*shortdescription[^"]*"[^>]*>(.-)</div>'
            local short_desc_match = html:match(short_desc_pat)
            if short_desc_match then
                short_description = short_desc_match:gsub('&[^;]+;', ' '):gsub('%s+', ' '):match('^%s*(.-)%s*$')
                if short_description == '' then
                    short_description = nil
                end
            end

            -- Fallback: query API's pageprops for short description
            if not short_description then
                local JSON = require("json")
                local props_url = string.format(
                    "https://%s.wikipedia.org/w/api.php?action=query&prop=pageprops&titles=%s&format=json",
                    wiki_lang or "en", socket_url.escape(wiki_title)
                )
                local props_ok, props_code, props_sink = wutil.httpGetJSON(props_url)
                if props_ok and props_code == 200 then
                    local props_parse_ok, props_data = pcall(JSON.decode, table.concat(props_sink))
                    if props_parse_ok and props_data and props_data.query and props_data.query.pages then
                        for _, props_page in pairs(props_data.query.pages) do
                            if props_page.pageprops and props_page.pageprops["wikibase-shortdesc"] then
                                short_description = props_page.pageprops["wikibase-shortdesc"]
                                break
                            end
                        end
                    end
                end
            end

            if result.title then
                resolved_title = result.title
            end
            -- Kept infoboxes are normally stripped (fixed width and float
            -- wreck a single-column reflowable layout); when kept, force
            -- them to span the full page width like wikitables.
            local infobox_full_width = G_reader_settings:isTrue("wikireader_show_infoboxes")

            -- Force a kept table to span the whole page width and drop any
            -- inline float, so body text can never sit beside it in the
            -- single-column reflowable layout. (floatleft/floatright class
            -- removal is handled separately by cleanElementClasses.)
            --
            -- NOTE: cleanElementClasses splices this return value into the
            -- tag via a gsub replacement where % is special, so any literal
            -- percent must survive as %% (decoded back to % by that final
            -- splice). The width/float declarations are therefore removed by
            -- *deleting* with a gsub (replacement "") and the "width:100%%"
            -- suffix is appended plain -- never pushed through a gsub
            -- replacement -- to avoid double-decoding it to "width:100".
            local function forceFullWidthStyle(style)
                style = style:gsub('width%s*:%s*[^;]+', '') -- existing fixed width
                style = style:gsub('float%s*:%s*[^;]+', '') -- inline float
                style = style:gsub(';%s*;+', ';'):gsub('^%s*;?%s*', ''):gsub(';%s*$', '')
                -- Any % left in the kept declarations must also be escaped
                -- for the final splice (e.g. font-size: 80%): each % becomes
                -- %% here, which the splice decodes back to a single %.
                style = style:gsub('%%', '%%%%')
                if style == "" then
                    return "width:100%%"
                end
                return style .. ';width:100%%'
            end

            -- Kept infoboxes: like forceFullWidthStyle, but also drops any
            -- inline font-size on the <table> itself. Speciesbox/Taxobox
            -- tables carry "font-size: 100%" (they opt out of the live
            -- site's 88% infobox shrink), which makes biology boxes render
            -- at full body size while every other infobox sits at the base
            -- stylesheet's table size (80%). Removing the override lets the
            -- same table rule apply to them. This works even when the user
            -- disables "Embedded Style" (the injected stylesheet.css and
            -- its table.infobox !important rule are ignored then, while
            -- inline styles may still apply). Runs BEFORE the %-escaping in
            -- forceFullWidthStyle, on the raw style text. Table borders are
            -- not handled here: htmlclean.borderTableCells applies them
            -- inline to infoboxes and wikitables alike (crengine ignores
            -- descendant selectors, so stylesheet rules can't reach cells).
            local function infoboxFullWidthStyle(style)
                style = style:gsub('font%-size%s*:%s*[^;]+;%s*', '')
                style = style:gsub('font%-size%s*:%s*[^;]+', '')
                return forceFullWidthStyle(style)
            end

            -- Strip clutter tables: chronology/nav/sidebar/route-map boxes
            -- are always dropped; infoboxes only while full-width mode is
            -- off (the default).
            local stripped_tables = { "navbox", "sidebar", "vertical-navbox", "rmbox" }
            if not infobox_full_width then
                table.insert(stripped_tables, "infobox")
            end
            html = htmlclean.stripElementsByClass(html, "table", stripped_tables)

            -- The "Temporal range" bar biology infoboxes render via
            -- {{Geological range}} is absolute-positioned CSS art (a
            -- 250px-wide row of colored era boxes) that wrecks the
            -- reflowable layout; the useful text summary it decorates sits
            -- just before it. Matched by id (MediaWiki emits
            -- id="Timeline-row").
            html = htmlclean.stripElementsByAttr(html, "div", "id", { "timeline-row" })

            html = htmlclean.cleanElementClasses(html, "table", { "wikitable" }, { "floatleft", "floatright" }, forceFullWidthStyle)
            if infobox_full_width then
                html = htmlclean.cleanElementClasses(html, "table", { "infobox" }, { "floatleft", "floatright" }, infoboxFullWidthStyle)
                -- {{Infobox element}}'s periodic-table diagram is
                -- TemplateStyles/CSS art crengine can't render; drop it
                -- (with its header row) before the other infobox passes.
                html = htmlclean.stripElementPeriodicTable(html)
                -- Kept infobox: drop media cells, keep text data and inline
                -- names. Must run before the QR pass.
                html = htmlclean.stripImageCells(html)
                -- Center full-width infobox rows inline (the base stylesheet
                -- has no .infobox rules and crengine ignores descendant
                -- selectors), mirroring Wikipedia's own alignment.
                html = htmlclean.centerInfoboxCells(html)
            end
            -- Border infoboxes and wikitables as grids, inline (see
            -- borderTableCells: crengine ignores descendant selectors, so
            -- stylesheet rules can't reach the cells).
            html = htmlclean.borderTableCells(html)
            if qr_enabled then
                -- Keep media boxes intact so their images can be QR-coded.
                html = htmlclean.stripElementsByClass(html, "div", { "catlinks", "navbox", "vertical-navbox", "side-box", "spoken-wikipedia", "shortdescription" })
            else
                -- Drop media boxes (and their captions) entirely.
                html = htmlclean.stripElementsByClass(html, "div", { "thumb", "catlinks", "navbox", "vertical-navbox", "side-box", "spoken-wikipedia", "shortdescription" })
                html = htmlclean.stripElementsByClass(html, "ul", { "gallery" })
            end
            html = htmlclean.cleanElementClasses(html, "div", { "quotebox", "pullquote" }, { "floatleft", "floatright" }, true)
            html = htmlclean.stripElementsByClass(html, "span", { "geo-inline-hidden" })
            html = htmlclean.mergeQuoteCites(html)
            -- "Disable hyperlinks": unwrap internal article links, keep
            -- reference/external ones. Runs before the QR pass.
            if G_reader_settings:isTrue("wikireader_disable_hyperlinks") then
                html = htmlclean.stripArticleLinks(html)
            end
            -- Media figures: in QR mode qrimage turns each <img>/<video>/<audio>
            -- into a QR code; otherwise drop the media boxes and players.
            if not qr_enabled then
                html = htmlclean.stripElementsByAttr(html, "figure", "typeof", { "mw:file", "mw:image", "mw:video", "mw:audio" })
                html = html:gsub("<audio.-</audio%s*>", "")
            end
            html = latex.replaceMathElements(html)
            -- Render cladograms (Template:Clade phylogeny trees) as text
            -- diagrams, since crengine cannot draw their CSS border lines.
            html = cladogram.replaceCladograms(html)
            -- Replace each media element with a QR placeholder; PNGs are
            -- stitched in from the Archiver hooks below.
            if qr_enabled then
                html = qrimage.replaceImagesWithQr(html, qr_images, qr_size, lang)
                -- Figures' mw-halign-* classes select base-stylesheet rules
                -- (floats, wide margins) that outrank the injected
                -- attribute-only selectors; drop them so the full-width
                -- figure rules below always win (see htmlclean.lua).
                html = htmlclean.stripFigureHalign(html)
                -- {{Multiple image}} uses flexbox, unsupported by crengine;
                -- rewrite the box into a native <table>.
                html = htmlclean.restructureMultiImages(html)
            end

            -- Extract hatnotes and wrap section notices
            local notices, rest = htmlclean.extractLeadingNotices(html)
            rest = htmlclean.wrapSectionNotices(rest)
            if notices ~= "" then
                html = string.format(
                    [[<div class="wikireader-notices">%s</div><hr class="koreaderwikifrontpage"/>%s]],
                    notices, rest
                )
            else
                html = [[<hr class="koreaderwikifrontpage"/>]] .. rest
            end

            result.text["*"] = html
        end
        return result
    end

    -- Patch the Archiver to fix front matter, add the short description,
    -- and inject stylesheet rules.
    local original_addFileFromMemory = Archiver.Writer.addFileFromMemory
    Archiver.Writer.addFileFromMemory = function(self, entry_path, content, mtime)
        if entry_path == "OEBPS/content.html" then
            content = htmlclean.stripElementsByClass(content, "p", { "koreaderwikifrontpage" })
            content = htmlclean.stripElementsByClass(content, "h5", { "koreaderwikifrontpage" })
            content = content:gsub('<hr class="koreaderwikifrontpage"%s*/?>', "", 1)
            if short_description and short_description ~= "" then
                content = content:gsub(
                    '(<h1[^>]*>.-</h1>)',
                    '%1\n<div style="font-style:italic; color:#666; margin-top:0.2em; margin-bottom:1em; text-align:center;">' .. short_description .. '</div>'
                )
            end
            if resolved_title then
                content = content:gsub('(<title>).-(</title>)', '%1' .. resolved_title .. '%2')
            end
            -- Swap each QR placeholder for a real <img> and embed the PNGs.
            -- This hook has the Archiver writer (`self`); createEpub never
            -- sees the QR images.
            if next(qr_images) then
                content = content:gsub('<span class="wikireader%-qrimg" data%-qrindex="(%d+)"></span>', function(idx)
                    local qr = qr_images[tonumber(idx)]
                    if not qr then
                        return ""
                    end
                    local title = qr.url:gsub("&", "&amp;"):gsub('"', "&quot;")
                    return string.format(
                        '<img src="%s" width="%d" height="%d" class="wikireader-qr" alt="QR code for image" title="%s"/>',
                        qr.path, qr_size, qr_size, title)
                end)
                for _, qr in ipairs(qr_images) do
                    original_addFileFromMemory(self, "OEBPS/" .. qr.path, qr.png, mtime)
                end
            end
        elseif entry_path == "OEBPS/content.opf" then
            if resolved_title then
                content = content:gsub('(<dc:title>).-(</dc:title>)', '%1' .. resolved_title .. '%2')
            end
            if next(qr_images) then
                for idx, qr in ipairs(qr_images) do
                    content = content:gsub("</manifest>", string.format(
                        '<item id="qr%05d" href="%s" media-type="image/png"/>\n  </manifest>',
                        idx, qr.path))
                end
            end
        elseif entry_path == "OEBPS/toc.ncx" then
            if resolved_title then
                content = content:gsub('(<docTitle>%s*<text>).-(</text>%s*</docTitle>)', '%1' .. resolved_title .. '%2')
                content = content:gsub('(<navPoint[^>]*>%s*<navLabel>%s*<text>).-(</text>%s*</navLabel>%s*<content src="content%.html"/>)', '%1' .. resolved_title .. '%2')
            end
        elseif entry_path == "OEBPS/stylesheet.css" then
            -- QR-code images (see qrimage.lua): KOReader's base stylesheet
            -- zeroes the top padding of figure/gallery boxes when NO images
            -- are included (real thumbnails would get padding-top: 0.5em).
            -- A QR PNG is a flat rectangle with no strut, so without this
            -- it would sit flush against the top border. The base stylesheet
            -- also boxes thumbnails with "border: dotted 1px black"; restyle
            -- all QR boxes to a lighter dashed border to match the notices.
            if qr_enabled then
                content = content .. [[

figure[typeof~='mw:File/Thumb'],
figure[typeof~='mw:File/Frame'] {
    padding-top: 0.5em;
}
li.gallerybox {
    padding-top: 0.5em !important;
}

/* {{Multiple image}} boxes, rewritten into a native <table> by
   htmlclean.restructureMultiImages (crengine cannot do the template's
   flexbox layout). Mirror the figure-box styling of the base stylesheet
   (no page split, and -- unlike the floated article layout -- full width),
   but with the dashed QR-box border. The template's inline width
   (e.g. 492px) is overridden below so very wide boxes never overflow the
   page; the cells then shrink proportionally. */
table.wikireader-tmulti {
    border: 1px dashed #aaa;
    margin: 0.5em 0 0.5em 0;
    padding: 0 0.5em 0 0.5em;
    text-align: center;
    font-size: 90%;
    page-break-inside: avoid;
}

/* Image boxes span the full text width instead of keeping the article's
   own float, width and alignment (base stylesheet's float: right,
   33%/25% shares, Parsoid's inline style="width: NNNpx"). Selectors
   mirror the base stylesheet's (including its :dir(rtl) variant) so
   these later !important rules win the cascade; the base rules for
   .mw-halign-* figures never come into play because htmlclean strips
   those classes. */
figure[typeof~='mw:File/Thumb'],
figure[typeof~='mw:File/Frame'] {
    border: 1px dashed #aaa;
    width: 100% !important;
    max-width: 100% !important;
    margin: 0.5em 0 0.5em 0 !important;
}
body > div > figure[typeof~='mw:File/Thumb'],
body > div > figure[typeof~='mw:File/Frame'],
body > div:dir(rtl) > figure[typeof~='mw:File/Thumb'],
body > div:dir(rtl) > figure[typeof~='mw:File/Frame'] {
    float: none !important;
    clear: none !important;
    margin: 0.5em 0 0.5em 0 !important;
}
li.gallerybox {
    border: 1px dashed #aaa;
    width: 100% !important;
    margin: 0.5em 0 0.5em 0 !important;
}
/* The thumbinner's inline "width:NNNpx;max-width:NNNpx" lands on the
   rewritten table; max-width is what actually shrinks the box (width
   alone loses to nothing but the cap still applies), so it must be
   overridden too. */
table.wikireader-tmulti {
    width: 100% !important;
    max-width: 100% !important;
    margin: 0.5em 0 0.5em 0 !important;
}
]]
            end
            if infobox_full_width then
                -- Kept full-width infoboxes: mirror Wikipedia's own infobox
                -- alignment. The base stylesheet has no .infobox rules, so
                -- full-width data rows (office tenure, term dates, etc., in
                -- .infobox-full-data/.infobox-header/.infobox-subheader/
                -- .infobox-above/.infobox-below cells) would fall back to
                -- left-aligned. Label/data pairs are already left-aligned
                -- via the inline style="text-align:left" Wikipedia emits on
                -- .infobox-label cells, so only these rows need centering.
                content = content .. [[

.infobox .infobox-title,
.infobox .infobox-above,
.infobox .infobox-header,
.infobox .infobox-subheader,
.infobox .infobox-image,
.infobox .infobox-full-data,
.infobox .infobox-below {
  text-align: center;
}

/* Normalize the box text size across all infobox kinds. On the live site
   MediaWiki:Common.css shrinks every infobox to 88%, but Speciesbox/Taxobox
   opt OUT of that with their own "font-size: 100%" -- carried either inline
   on the table ("infobox biota") or in an embedded TemplateStyles block
   ("biota-infobox"). In the EPUB there is no site-wide 88% shrink at all:
   KOReader's base stylesheet renders every table at 80% of body size,
   which is what normal kept infoboxes display at -- so biology boxes alone
   ended up noticeably larger than every other infobox. Force the table
   back onto that same footing; !important is required because the inline
   "font-size: 100%" would otherwise outrank any plain stylesheet rule.
   Per-cell sizes (e.g. the 85% "Temporal range" line) still scale
   relative to this, and nested tables keep the base stylesheet's
   font-size:100%, i.e. they render at this same size once. */
table.infobox {
  font-size: 80% !important;
}
]]
            end
            content = content .. [[

.wikireader-notices {
  border: 1px solid #aaa;
  padding: 0.6em 0.8em;
  margin: 0 0 1em 0;
  font-style: italic;
  font-size: 80%;
}

blockquote {
  background: #f4f4f4;
  border-left: 3px solid #ccc;
  padding: 0.5em 0.8em;
  margin: 0.5em 0;
  font-style: italic;
}

/* Attribution line of Template:Quote, merged inside blockquote by
   htmlclean.mergeQuoteCites(). Right-aligned, normal weight and slightly
   smaller so it reads as a distinct " — who said it" trailing note. */
.wikireader-cite {
  text-align: right;
  font-style: normal;
  font-size: 85%;
  margin-top: 0.4em;
}

/* Fallback in case any templatequotecite div was not merged into a
   blockquote, so it never renders as a bare dangling line. */
.templatequotecite {
  text-align: right;
  font-style: italic;
  font-size: 85%;
  margin: 0.2em 0 0.8em 0;
}

.wikireader-math {
  white-space: nowrap;
}

/* Cladogram (phylogeny tree) diagrams, converted to box-drawing text by
   cladogram.lua. The base stylesheet already keeps <pre> left-aligned;
   shrink the monospace a touch and keep lines from stretching across the
   full page so the tree reads as one compact diagram. */
pre.wikireader-cladogram {
  font-size: 90%;
  line-height: 1.25;
  border: 1px solid #888;
  padding: 0.6em 0.8em;
  margin: 0 0 1em 0;
}
]]
        end
        return original_addFileFromMemory(self, entry_path, content, mtime)
    end

    Trapper:wrap(function()
        local ok, success = pcall(Wikipedia.createEpub, Wikipedia, epub_path, title, lang, false)
        -- Always restore all patches
        Wikipedia.wiki_phtml_params.redirects = original_phtml_redirects
        Wikipedia.getFullPageHtml = original_getFullPageHtml
        Archiver.Writer.addFileFromMemory = original_addFileFromMemory
        if ok and success then
            local used_path = epub_path
            if resolved_title and resolved_title ~= title then
                local new_path = cache.getCachePath(resolved_title, lang)
                if new_path ~= epub_path then
                    os.rename(epub_path, new_path)
                    DocSettings.updateLocation(epub_path, new_path)
                    used_path = new_path
                end
            end
            callback(true, used_path, resolved_title)
        else
            Trapper:reset()
            callback(false)
        end
    end)
end

--[[-------------------------------------------------------------------------
Single-page EPUB writer (shared by the standalone builders)
--]]

-- Writes one XHTML page plus stylesheet and package/NCX metadata for the
-- standalone helper pages (search results, category lists, main page),
-- which don't go through Wikipedia.createEpub(). Returns true on success.
local function writeSinglePageEpub(epub_path, title, lang, bookid_prefix, html_content, css)
    local mtime = os.time()

    local epub = Archiver.Writer:new{}
    local epub_path_tmp = epub_path .. ".tmp"
    if not epub:open(epub_path_tmp, "epub") then
        return false
    end

    epub:setZipCompression("store")
    epub:addFileFromMemory("mimetype", "application/epub+zip", mtime)
    epub:setZipCompression("deflate")

    epub:addFileFromMemory("META-INF/container.xml", [[
<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>]], mtime)

    local safe_title = title:gsub("[^%w]", "_")
    local bookid = string.format("%s_%s_%s_%d", bookid_prefix, lang, safe_title, mtime)
    local opf = string.format([[<?xml version='1.0' encoding='utf-8'?>
<package xmlns="http://www.idpf.org/2007/opf"
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        unique-identifier="bookid" version="2.0">
  <metadata>
    <dc:title>%s</dc:title>
    <dc:identifier id="bookid">%s</dc:identifier>
    <dc:language>%s</dc:language>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="content" href="content.html" media-type="application/xhtml+xml"/>
    <item id="css" href="stylesheet.css" media-type="text/css"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="content"/>
  </spine>
</package>
]], title, bookid, lang)
    epub:addFileFromMemory("OEBPS/content.opf", opf, mtime)
    epub:addFileFromMemory("OEBPS/content.html", html_content, mtime)
    epub:addFileFromMemory("OEBPS/stylesheet.css", css, mtime)

    local ncx = string.format([[
<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="%s"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle>
    <text>%s</text>
  </docTitle>
  <navMap>
    <navPoint id="navpoint-1" playOrder="1">
      <navLabel>
        <text>%s</text>
      </navLabel>
      <content src="content.html"/>
    </navPoint>
  </navMap>
</ncx>
]], bookid, title, title)
    epub:addFileFromMemory("OEBPS/toc.ncx", ncx, mtime)
    epub:close()

    os.rename(epub_path_tmp, epub_path)
    return true
end

--[[-------------------------------------------------------------------------
Search results EPUB builder
--]]

-- Build a minimal EPUB from a list of Wikipedia search results. Each
-- result is a clickable link the plugin's link handler can intercept.
-- If custom_title is provided, it's used as the page heading instead of
-- "Search results for...".
function M.buildSearchEpub(epub_path, query, lang, results, callback, custom_title)
    local display_title = custom_title or query
    local is_search = not custom_title

    local html_parts = {}
    table.insert(html_parts, '<?xml version="1.0" encoding="utf-8"?>\n')
    table.insert(html_parts, '<!DOCTYPE html>\n')
    table.insert(html_parts, '<html xmlns="http://www.w3.org/1999/xhtml">\n')
    table.insert(html_parts, '<head>\n')
    table.insert(html_parts, '<meta charset="utf-8"/>\n')
    table.insert(html_parts, '<link rel="stylesheet" type="text/css" href="stylesheet.css"/>\n')
    table.insert(html_parts, '<title>')
    if is_search then
        table.insert(html_parts, string.format('Search results for "%s"', query))
    else
        table.insert(html_parts, display_title)
    end
    table.insert(html_parts, '</title>\n')
    table.insert(html_parts, '</head>\n')
    table.insert(html_parts, '<body>\n')
    if is_search then
        table.insert(html_parts, '<h1 class="koreaderwikifrontpage">Search results</h1>\n')
        table.insert(html_parts, '<p class="koreaderwikifrontpage">')
        table.insert(html_parts, string.format('for "%s"', query))
        table.insert(html_parts, '</p>\n')
        table.insert(html_parts, '<hr class="koreaderwikifrontpage"/>\n')
    else
        table.insert(html_parts, '<h1 class="koreaderwikifrontpage">')
        table.insert(html_parts, display_title)
        table.insert(html_parts, '</h1>\n')
        table.insert(html_parts, '<hr class="koreaderwikifrontpage"/>\n')
    end

    for _, result in ipairs(results) do
        local result_title = result.title
        local snippet = (result.snippet or ""):gsub("<[^>]*>", "")
        snippet = util.htmlEntitiesToUtf8(snippet)
        if snippet ~= "" and not snippet:match("[.!?…]$") then
            snippet = snippet .. "…"
        end
        result_title = result_title:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
        snippet = snippet:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
        local link = string.format('https://%s.wikipedia.org/wiki/%s', lang, socket_url.escape(result.title))

        if snippet == "" then
            table.insert(html_parts, string.format(
                '<p class="article-link"><a href="%s">· %s</a></p>\n',
                link, result_title))
        else
            table.insert(html_parts, string.format(
                '<p class="article-link"><a href="%s">· %s</a></p>\n<p class="snippet">%s</p>\n',
                link, result_title, snippet))
        end
    end

    table.insert(html_parts, '</body>\n')
    table.insert(html_parts, '</html>\n')
    local html_content = table.concat(html_parts)

    local css = [[
body {
  text-align: justify;
}
h1.koreaderwikifrontpage {
  text-align: center;
  margin-top: 0;
}
p.koreaderwikifrontpage {
  font-style: italic;
  text-align: center;
  margin-bottom: 1em;
  text-indent: 0;
}
hr.koreaderwikifrontpage {
  margin-left: 20%;
  margin-right: 20%;
  margin-bottom: 1.2em;
}
.search-result {
  margin-bottom: 1em;
}
p.article-link {
  margin: 0.4em 0;
}
p.snippet {
  margin: 0 0 0.8em 0;
  font-size: 80%;
}
a {
  text-decoration: underline;
  color: inherit;
}
]]

    if not writeSinglePageEpub(epub_path, display_title, lang, "search", html_content, css) then
        callback(false)
        return
    end
    callback(true, epub_path)
end

--[[-------------------------------------------------------------------------
Category EPUB builder
--]]

-- Build an EPUB for a level of the category tree (subcategories plus any
-- leaf articles), then open it. Subcategories use a special URL format
-- that the link handler intercepts; articles use standard Wikipedia URLs.
function M.buildCategoryEpub(nodes, title, lang, direct_articles)
    local html_parts = {}
    table.insert(html_parts, '<?xml version="1.0" encoding="utf-8"?>\n')
    table.insert(html_parts, '<!DOCTYPE html>\n')
    table.insert(html_parts, '<html xmlns="http://www.w3.org/1999/xhtml">\n')
    table.insert(html_parts, '<head>\n')
    table.insert(html_parts, '<meta charset="utf-8"/>\n')
    table.insert(html_parts, '<link rel="stylesheet" type="text/css" href="stylesheet.css"/>\n')
    table.insert(html_parts, '<title>')
    table.insert(html_parts, title)
    table.insert(html_parts, '</title>\n')
    table.insert(html_parts, '</head>\n')
    table.insert(html_parts, '<body>\n')
    table.insert(html_parts, '<h1>')
    table.insert(html_parts, title)
    table.insert(html_parts, '</h1>\n')
    table.insert(html_parts, '<hr/>\n')

    for _, node in ipairs(nodes) do
        local escaped_title = node.title:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
        local link = string.format('https://%s.wikipedia.org/wiki/Wikipedia:Featured_articles#section_%s',
            lang, node.section_index)
        table.insert(html_parts, string.format(
            '<p class="category-link"><a href="%s">▸ %s</a></p>\n',
            link, escaped_title))
    end

    if direct_articles and #direct_articles > 0 then
        if #nodes > 0 then
            table.insert(html_parts, '<hr/>\n')
        end
        for _, article in ipairs(direct_articles) do
            local escaped_title = article.title:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
            local link = string.format('https://%s.wikipedia.org/wiki/%s', lang, socket_url.escape(article.title))
            table.insert(html_parts, string.format(
                '<p class="article-link"><a href="%s">· %s</a></p>\n',
                link, escaped_title))
        end
    end

    table.insert(html_parts, '</body>\n')
    table.insert(html_parts, '</html>\n')
    local html_content = table.concat(html_parts)

    local css = [[
body {
  text-align: justify;
}
h1 {
  text-align: center;
  margin-top: 0;
}
h2 {
  font-size: 120%;
  margin-top: 1em;
}
hr {
  margin-left: 20%;
  margin-right: 20%;
  margin-bottom: 1em;
}
p.category-link {
  margin: 0.5em 0;
}
p.article-link {
  margin: 0.3em 0;
}
a {
  text-decoration: underline;
  color: inherit;
}
]]

    local epub_path = cache.getCachePath("__category__" .. title, lang)
    if not writeSinglePageEpub(epub_path, title, lang, "category", html_content, css) then
        return false
    end
    return true, epub_path
end

--[[-------------------------------------------------------------------------
Main page EPUB builder
--]]

-- Builds the "Wikipedia main page" EPUB from mainpage.fetchSections()
-- output. The date is part of the cache key and title: each day is its
-- own cache entry, so a cached copy never outlives the day's news.
function M.buildMainPageEpub(date_str, lang, sections)
    local year, month, day = date_str:match("^(%d+)%-(%d+)%-(%d+)$")
    local display_date = date_str
    if year then
        -- hour=12 keeps the DST-sensitive %B conversion away from
        -- midnight edges; the C locale gives English month names.
        local t = os.time{ year = tonumber(year), month = tonumber(month), day = tonumber(day), hour = 12 }
        display_date = string.format("%s %d, %d", os.date("%B", t), day, year)
    end

    local page_title = _("Wikipedia main page")
    local display_title = page_title .. " (" .. display_date .. ")"

    local html_parts = {}
    table.insert(html_parts, '<?xml version="1.0" encoding="utf-8"?>\n')
    table.insert(html_parts, '<!DOCTYPE html>\n')
    table.insert(html_parts, '<html xmlns="http://www.w3.org/1999/xhtml">\n')
    table.insert(html_parts, '<head>\n')
    table.insert(html_parts, '<meta charset="utf-8"/>\n')
    table.insert(html_parts, '<link rel="stylesheet" type="text/css" href="stylesheet.css"/>\n')
    table.insert(html_parts, '<title>')
    table.insert(html_parts, display_title)
    table.insert(html_parts, '</title>\n')
    table.insert(html_parts, '</head>\n')
    table.insert(html_parts, '<body>\n')
    table.insert(html_parts, '<h1 class="koreaderwikifrontpage">')
    table.insert(html_parts, page_title)
    table.insert(html_parts, '</h1>\n')
    table.insert(html_parts, '<p class="koreaderwikifrontpage">')
    table.insert(html_parts, display_date)
    table.insert(html_parts, '</p>\n')
    table.insert(html_parts, '<hr class="koreaderwikifrontpage"/>\n')

    local section_headings = {
        itn = _("In the news"),
        dyk = _("Did you know"),
        otd = _("On this day"),
    }
    for _, key in ipairs({ "itn", "dyk", "otd" }) do
        if sections[key] then
            table.insert(html_parts, '<h2 class="wikireader-mainpage-section">')
            table.insert(html_parts, section_headings[key])
            table.insert(html_parts, '</h2>\n')
            table.insert(html_parts, sections[key])
            table.insert(html_parts, '\n')
        end
    end

    table.insert(html_parts, '</body>\n')
    table.insert(html_parts, '</html>\n')
    local html_content = table.concat(html_parts)

    local css = [[
body {
  text-align: justify;
}
h1.koreaderwikifrontpage {
  text-align: center;
  margin-top: 0;
}
p.koreaderwikifrontpage {
  font-style: italic;
  text-align: center;
  margin-bottom: 1em;
  text-indent: 0;
}
hr.koreaderwikifrontpage {
  margin-left: 20%;
  margin-right: 20%;
  margin-bottom: 1.2em;
}
h2.wikireader-mainpage-section {
  font-size: 120%;
  border-bottom: 1px solid #aaa;
  padding-bottom: 0.2em;
  margin-top: 1em;
}
/* Match article EPUBs' link style; otherwise crengine's default blue shows */
a {
  text-decoration: underline;
  color: inherit;
}
]]

    local epub_path = cache.getHelperCachePath("__mainpage__", date_str, lang)
    if not writeSinglePageEpub(epub_path, display_title, lang, "mainpage", html_content, css) then
        return false
    end
    return true, epub_path
end

return M
