-- EPUB building for WikiReader.
-- Wraps KOReader's built-in Wikipedia.createEpub() with HTML cleanup
-- (stripping navboxes, removing image captions, etc.; converting math
-- formulas to readable text; extracting hatnotes into bordered boxes).
-- Infobox tables are stripped by default; the "Show infoboxes"
-- setting keeps them instead, forced to span the full page
-- width like wikitables. Also provides standalone EPUB builders for
-- search results and category navigation pages.

local Archiver = require("ffi/archiver")
local DocSettings = require("docsettings")
local Trapper = require("ui/trapper")
local Wikipedia = require("ui/wikipedia")
local socket_url = require("socket.url")
local util = require("util")
local logger = require("logger")
local _ = require("gettext")

local cache = require("wikireader-cache")
local cladogram = require("cladogram")
local htmlclean = require("htmlclean")
local latex = require("latex")
local qrimage = require("qrimage")
local wutil = require("wikiutil")

local M = {}

--[[-------------------------------------------------------------------------
Full article EPUB builder
--]]

-- Fetches and converts an article, with images permanently disabled and
-- a handful of clutter elements stripped from the HTML before it's ever
-- handed to createEpub(): infobox tables (unless the "Show infoboxes"
-- option is on, see below), the category list at the bottom of the
-- article, etc.
--
-- When "media as QR codes" is enabled (the default), media boxes (and
-- their captions) are kept in the document, but each image or
-- audio/video item is replaced by a small QR code pointing at that
-- media's File: description page -- generated on the fly and embedded in
-- the EPUB, so nothing is ever downloaded. See qrimage.lua.
--
-- A kept infobox keeps its text data and drops its images: genuine
-- media cells (lead portraits, maps, emblems, ... ) are removed outright by
-- htmlclean.stripImageCells before the QR pass (so no QR codes appear
-- inside the box), while the small inline flags next to a combatant's /
-- commander's name are removed and the name/link/footnote text is kept.
-- See the comment around the stripImageCells call below.
--
-- See the detailed comment in the original main.lua for full rationale.
function M.buildEpub(epub_path, title, lang, callback)

    -- Will hold the short description extracted from HTML
    local short_description = nil
    -- Will hold the resolved article title from the API response
    local resolved_title = nil

    -- QR-code images: whether the article's images become QR codes of their
    -- URLs (keeping the boxes and captions), and at what display size. The
    -- QR PNGs are generated by qrimage during the HTML pass below, collected
    -- in `qr_images`, then stitched into the EPUB from the Archiver hooks.
    local qr_enabled = G_reader_settings:nilOrTrue("wikireader_qr_media")
    local qr_size = G_reader_settings:readSetting("wikireader_qr_size") or qrimage.DEFAULT_QR_SIZE
    local qr_images = {}

    -- Patch redirects support
    local original_phtml_redirects = Wikipedia.wiki_phtml_params.redirects
    Wikipedia.wiki_phtml_params.redirects = ""

    local original_getFullPageHtml = Wikipedia.getFullPageHtml
    Wikipedia.getFullPageHtml = function(self, wiki_title, wiki_lang)
        local ok, result = pcall(original_getFullPageHtml, self, wiki_title, wiki_lang)
        if not ok or not result then
            return nil
        end
        if result and result.text and result.text["*"] then
            local html = result.text["*"]

            -- Extract short description from the HTML before stripping it.
            local short_desc_pat = '<div[^>]*class="[^"]*shortdescription[^"]*"[^>]*>(.-)</div>'
            local short_desc_match = html:match(short_desc_pat)
            if short_desc_match then
                short_description = short_desc_match:gsub('&[^;]+;', ' '):gsub('%s+', ' '):match('^%s*(.-)%s*$')
                if short_description == '' then
                    short_description = nil
                end
            end

            -- Fallback: query API's pageprops for short description
            if not short_description then
                local JSON = require("json")
                local props_url = string.format(
                    "https://%s.wikipedia.org/w/api.php?action=query&prop=pageprops&titles=%s&format=json",
                    wiki_lang or "en", socket_url.escape(wiki_title)
                )
                local props_ok, props_code, props_sink = wutil.httpGetJSON(props_url)
                if props_ok and props_code == 200 then
                    local props_parse_ok, props_data = pcall(JSON.decode, table.concat(props_sink))
                    if props_parse_ok and props_data and props_data.query and props_data.query.pages then
                        for _, props_page in pairs(props_data.query.pages) do
                            if props_page.pageprops and props_page.pageprops["wikibase-shortdesc"] then
                                short_description = props_page.pageprops["wikibase-shortdesc"]
                                break
                            end
                        end
                    end
                end
            end

            -- Capture the resolved title from the API response
            if result.title then
                resolved_title = result.title
            end

            -- Infobox tables are normally stripped (their default fixed side
            -- width and float make body text wrap around them, which wrecks
            -- a single-column reflowable layout). When "Show infoboxes" is
            -- enabled, they are kept instead and forced to span the full page
            -- width exactly like the wikitables below, so the box reads as a
            -- normal full-width table. Its media cells (images and captions)
            -- are dropped by stripImageCells below -- QR codes or real images
            -- would only clutter the box.
            local infobox_full_width = G_reader_settings:isTrue("wikireader_show_infoboxes")

            -- Force a kept table to span the whole page width and drop any
            -- inline float, so body text can never sit beside it in the
            -- single-column reflowable layout. (floatleft/floatright class
            -- removal is handled separately by cleanElementClasses.)
            --
            -- NOTE: cleanElementClasses splices this return value into the
            -- tag via a gsub replacement where % is special, so any literal
            -- percent must survive as %% (decoded back to % by that final
            -- splice). The width/float declarations are therefore removed by
            -- *deleting* with a gsub (replacement "") and the "width:100%%"
            -- suffix is appended plain -- never pushed through a gsub
            -- replacement -- to avoid double-decoding it to "width:100".
            local function forceFullWidthStyle(style)
                style = style:gsub('width%s*:%s*[^;]+', '') -- existing fixed width
                style = style:gsub('float%s*:%s*[^;]+', '') -- inline float
                style = style:gsub(';%s*;+', ';'):gsub('^%s*;?%s*', ''):gsub(';%s*$', '')
                -- Any % left in the kept declarations must also be escaped
                -- for the final splice (e.g. font-size: 80%): each % becomes
                -- %% here, which the splice decodes back to a single %.
                style = style:gsub('%%', '%%%%')
                if style == "" then
                    return "width:100%%"
                end
                return style .. ';width:100%%'
            end

            -- Kept infoboxes: like forceFullWidthStyle, but also drops any
            -- inline font-size on the <table> itself. Speciesbox/Taxobox
            -- tables carry "font-size: 100%" (they opt out of the live
            -- site's 88% infobox shrink), which makes biology boxes render
            -- at full body size while every other infobox sits at the base
            -- stylesheet's table size (80%). Removing the override lets the
            -- same table rule apply to them. This works even when the user
            -- disables "Embedded Style" (the injected stylesheet.css and
            -- its table.infobox !important rule are ignored then, while
            -- inline styles may still apply). Runs BEFORE the %-escaping in
            -- forceFullWidthStyle, on the raw style text.
            local function infoboxFullWidthStyle(style)
                style = style:gsub('font%-size%s*:%s*[^;]+;%s*', '')
                style = style:gsub('font%-size%s*:%s*[^;]+', '')
                return forceFullWidthStyle(style)
            end

            -- Strip clutter tables: chronology/nav/sidebar/route-map boxes
            -- are always dropped; infoboxes only while full-width mode is
            -- off (the default).
            local stripped_tables = { "navbox", "sidebar", "vertical-navbox", "rmbox" }
            if not infobox_full_width then
                table.insert(stripped_tables, "infobox")
            end
            html = htmlclean.stripElementsByClass(html, "table", stripped_tables)

            -- The geologic time-scale bar ("Temporal range") that biology
            -- infoboxes (Speciesbox etc.) render via {{Geological range}} is
            -- pure absolute-positioned CSS art: a fixed 250px-wide row of
            -- colored era boxes (PreꞒ Ꞓ O S D C P T J K Pg N) topped by the
            -- species' range marker. It carries id="Timeline-row" and holds
            -- the whole drawing, marker included. It wrecks the reflowable
            -- infobox layout, while the text summary it decorates ("Temporal
            -- range: Early Pleistocene – Recent … Ma") sits just before it,
            -- so dropping the bar keeps exactly the useful text. Matched by
            -- id, not class (MediaWiki emits it as id="Timeline-row").
            html = htmlclean.stripElementsByAttr(html, "div", "id", { "timeline-row" })

            html = htmlclean.cleanElementClasses(html, "table", { "wikitable" }, { "floatleft", "floatright" }, forceFullWidthStyle)
            if infobox_full_width then
                html = htmlclean.cleanElementClasses(html, "table", { "infobox" }, { "floatleft", "floatright" }, infoboxFullWidthStyle)
                -- A kept infobox keeps its text data and drops images: genuine media
                -- cells (lead portrait, maps, emblem/symbol stacks, ...)
                -- are dropped along with their caption text, but the small
                -- inline flags next to a combatant's / commander's name are
                -- removed and the name/link/footnote text is kept (and the
                -- wide conservation-status badge banners are removed while
                -- the status text beneath them is kept), so battle / war
                -- infoboxes keep the named entities they list and biology
                -- infoboxes keep every "Conservation status" row's text.
                -- QR codes would clutter the box -- see htmlclean.stripImageCells
                -- (must run before the QR pass so no placeholder is created).
                html = htmlclean.stripImageCells(html)
                -- Center the box's full-width rows (title, section headers,
                -- office-tenure/term rows, footer) like Wikipedia does: the
                -- base stylesheet has no .infobox rules, and crengine's CSS
                -- may not reliably apply the descendant selectors we append
                -- to it, so the alignment is put inline on each cell where
                -- it always wins over any left-align defaults.
                html = htmlclean.centerInfoboxCells(html)
            end
            if qr_enabled then
                -- Keep image boxes: figure/gallery/div.thumb wrappers are
                -- left intact so their images can be QR-coded below.
                html = htmlclean.stripElementsByClass(html, "div", { "catlinks", "navbox", "vertical-navbox", "side-box", "spoken-wikipedia", "shortdescription" })
            else
                -- Original behaviour: drop image boxes (and their captions),
                -- legacy div.thumb boxes and whole galleries before conversion.
                html = htmlclean.stripElementsByClass(html, "div", { "thumb", "catlinks", "navbox", "vertical-navbox", "side-box", "spoken-wikipedia", "shortdescription" })
                html = htmlclean.stripElementsByClass(html, "ul", { "gallery" })
            end
            html = htmlclean.cleanElementClasses(html, "div", { "quotebox", "pullquote" }, { "floatleft", "floatright" }, true)
            html = htmlclean.stripElementsByClass(html, "span", { "geo-inline-hidden" })
            html = htmlclean.mergeQuoteCites(html)
            -- "Disable hyperlinks": unwrap every <a> pointing at another
            -- Wikipedia article (keeping its text); reference/footnote
            -- anchors and genuine external links stay clickable. Runs before
            -- the QR pass so media description links are gone by then.
            if G_reader_settings:isTrue("wikireader_disable_hyperlinks") then
                html = htmlclean.stripArticleLinks(html)
            end
            -- Media figures: in QR mode every media figure is kept, and
            -- qrimage turns each embedded <img>/<video>/<audio> into a QR
            -- code pointing at its File: description page (see qrimage.lua). Otherwise, original
            -- behaviour: drop all media figure boxes and stray audio
            -- players before conversion.
            if not qr_enabled then
                html = htmlclean.stripElementsByAttr(html, "figure", "typeof", { "mw:file", "mw:image", "mw:video", "mw:audio" })
                html = html:gsub("<audio.-</audio%s*>", "")
            end
            html = latex.replaceMathElements(html)
            -- Render cladograms (Template:Clade phylogeny trees) as text
            -- diagrams, since crengine cannot draw their CSS border lines.
            html = cladogram.replaceCladograms(html)
            -- Replace every image / video / audio element inside an image
            -- box with a QR-code placeholder (keeping the box and its
            -- caption). The actual QR PNGs are stitched in from the
            -- Archiver hooks below.
            if qr_enabled then
                html = qrimage.replaceImagesWithQr(html, qr_images, qr_size, lang)
            end

            -- Extract hatnotes and wrap section notices
            local notices, rest = htmlclean.extractLeadingNotices(html)
            rest = htmlclean.wrapSectionNotices(rest)
            if notices ~= "" then
                html = string.format(
                    [[<div class="wikireader-notices">%s</div><hr class="koreaderwikifrontpage"/>%s]],
                    notices, rest
                )
            else
                html = [[<hr class="koreaderwikifrontpage"/>]] .. rest
            end

            result.text["*"] = html
        end
        return result
    end

    -- Patch the Archiver to fix front matter, add short description, and
    -- inject stylesheet rules.
    local original_addFileFromMemory = Archiver.Writer.addFileFromMemory
    Archiver.Writer.addFileFromMemory = function(self, entry_path, content, mtime)
        if entry_path == "OEBPS/content.html" then
            content = htmlclean.stripElementsByClass(content, "p", { "koreaderwikifrontpage" })
            content = htmlclean.stripElementsByClass(content, "h5", { "koreaderwikifrontpage" })
            content = content:gsub('<hr class="koreaderwikifrontpage"%s*/?>', "", 1)
            if short_description and short_description ~= "" then
                content = content:gsub(
                    '(<h1[^>]*>.-</h1>)',
                    '%1\n<div style="font-style:italic; color:#666; margin-top:0.2em; margin-bottom:1em; text-align:center;">' .. short_description .. '</div>'
                )
            end
            if resolved_title then
                content = content:gsub('(<title>).-(</title>)', '%1' .. resolved_title .. '%2')
            end
            -- Swap each QR placeholder for a real <img> pointing at the
            -- generated PNG, and embed those PNGs into the archive. This is
            -- done here because this hook has the Archiver writer handle
            -- (`self`); createEpub itself never sees the QR images.
            if next(qr_images) then
                content = content:gsub('<span class="wikireader%-qrimg" data%-qrindex="(%d+)"></span>', function(idx)
                    local qr = qr_images[tonumber(idx)]
                    if not qr then
                        return ""
                    end
                    local title = qr.url:gsub("&", "&amp;"):gsub('"', "&quot;")
                    return string.format(
                        '<img src="%s" width="%d" height="%d" class="wikireader-qr" alt="QR code for image" title="%s"/>',
                        qr.path, qr_size, qr_size, title)
                end)
                for _, qr in ipairs(qr_images) do
                    original_addFileFromMemory(self, "OEBPS/" .. qr.path, qr.png, mtime)
                end
            end
        elseif entry_path == "OEBPS/content.opf" then
            if resolved_title then
                content = content:gsub('(<dc:title>).-(</dc:title>)', '%1' .. resolved_title .. '%2')
            end
            -- Register all generated QR images in the EPUB manifest.
            if next(qr_images) then
                for idx, qr in ipairs(qr_images) do
                    content = content:gsub("</manifest>", string.format(
                        '<item id="qr%05d" href="%s" media-type="image/png"/>\n  </manifest>',
                        idx, qr.path))
                end
            end
        elseif entry_path == "OEBPS/toc.ncx" then
            if resolved_title then
                content = content:gsub('(<docTitle>%s*<text>).-(</text>%s*</docTitle>)', '%1' .. resolved_title .. '%2')
                content = content:gsub('(<navPoint[^>]*>%s*<navLabel>%s*<text>).-(</text>%s*</navLabel>%s*<content src="content%.html"/>)', '%1' .. resolved_title .. '%2')
            end
        elseif entry_path == "OEBPS/stylesheet.css" then
            -- QR-code images (see qrimage.lua): KOReader's base stylesheet
            -- zeroes the top padding of figure/gallery boxes when NO images
            -- are included (real thumbnails would get padding-top: 0.5em).
            -- A QR code is a flat rectangle with no strut, so without this
            -- it would sit flush against the top dotted border. Restore the
            -- same top padding the base rule gives real images. (A margin-top
            -- on the <img> would be ignored: the figure is display: table,
            -- so the image becomes an anonymous table-cell.)
            if qr_enabled then
                content = content .. [[

figure[typeof~='mw:File/Thumb'],
figure[typeof~='mw:File/Frame'] {
    padding-top: 0.5em;
}
li.gallerybox {
    padding-top: 0.5em !important;
}
]]
            end
            if infobox_full_width then
                -- Kept full-width infoboxes: mirror Wikipedia's own infobox
                -- alignment. The base stylesheet has no .infobox rules, so
                -- full-width data rows (office tenure, term dates, etc., in
                -- .infobox-full-data/.infobox-header/.infobox-subheader/
                -- .infobox-above/.infobox-below cells) would fall back to
                -- left-aligned. Label/data pairs are already left-aligned
                -- via the inline style="text-align:left" Wikipedia emits on
                -- .infobox-label cells, so only these rows need centering.
                content = content .. [[

.infobox .infobox-title,
.infobox .infobox-above,
.infobox .infobox-header,
.infobox .infobox-subheader,
.infobox .infobox-image,
.infobox .infobox-full-data,
.infobox .infobox-below {
  text-align: center;
}

/* Normalize the box text size across all infobox kinds. On the live site
   MediaWiki:Common.css shrinks every infobox to 88%, but Speciesbox/Taxobox
   opt OUT of that with their own "font-size: 100%" -- carried either inline
   on the table ("infobox biota") or in an embedded TemplateStyles block
   ("biota-infobox"). In the EPUB there is no site-wide 88% shrink at all:
   KOReader's base stylesheet renders every table at 80% of body size,
   which is what normal kept infoboxes display at -- so biology boxes alone
   ended up noticeably larger than every other infobox. Force the table
   back onto that same footing; !important is required because the inline
   "font-size: 100%" would otherwise outrank any plain stylesheet rule.
   Per-cell sizes (e.g. the 85% "Temporal range" line) still scale
   relative to this, and nested tables keep the base stylesheet's
   font-size:100%, i.e. they render at this same size once. */
table.infobox {
  font-size: 80% !important;
}
]]
            end
            content = content .. [[

.wikireader-notices {
  border: 1px solid #888;
  padding: 0.6em 0.8em;
  margin: 0 0 1em 0;
  font-style: italic;
  font-size: 80%;
}

blockquote {
  background: #f4f4f4;
  border-left: 3px solid #ccc;
  padding: 0.5em 0.8em;
  margin: 0.5em 0;
  font-style: italic;
}

/* Attribution line of Template:Quote, merged inside blockquote by
   htmlclean.mergeQuoteCites(). Right-aligned, normal weight and slightly
   smaller so it reads as a distinct " — who said it" trailing note. */
.wikireader-cite {
  text-align: right;
  font-style: normal;
  font-size: 85%;
  margin-top: 0.4em;
}

/* Fallback in case any templatequotecite div was not merged into a
   blockquote, so it never renders as a bare dangling line. */
.templatequotecite {
  text-align: right;
  font-style: italic;
  font-size: 85%;
  margin: 0.2em 0 0.8em 0;
}

.wikireader-math {
  white-space: nowrap;
}

/* Cladogram (phylogeny tree) diagrams, converted to box-drawing text by
   cladogram.lua. The base stylesheet already keeps <pre> left-aligned;
   shrink the monospace a touch and keep lines from stretching across the
   full page so the tree reads as one compact diagram. */
pre.wikireader-cladogram {
  font-size: 90%;
  line-height: 1.25;
  border: 1px solid #888;
  padding: 0.6em 0.8em;
  margin: 0 0 1em 0;
}
]]
        end
        return original_addFileFromMemory(self, entry_path, content, mtime)
    end

    Trapper:wrap(function()
        local ok, success = pcall(Wikipedia.createEpub, Wikipedia, epub_path, title, lang, false)
        -- Always restore all patches
        Wikipedia.wiki_phtml_params.redirects = original_phtml_redirects
        Wikipedia.getFullPageHtml = original_getFullPageHtml
        Archiver.Writer.addFileFromMemory = original_addFileFromMemory
        if ok and success then
            local used_path = epub_path
            if resolved_title and resolved_title ~= title then
                local new_path = cache.getCachePath(resolved_title, lang)
                if new_path ~= epub_path then
                    os.rename(epub_path, new_path)
                    DocSettings.updateLocation(epub_path, new_path)
                    used_path = new_path
                end
            end
            callback(true, used_path, resolved_title)
        else
            Trapper:reset()
            callback(false)
        end
    end)
end

--[[-------------------------------------------------------------------------
Search results EPUB builder
--]]

-- Build a minimal EPUB from a list of Wikipedia search results. Each
-- result is a clickable link the plugin's link handler can intercept.
-- If custom_title is provided, it's used as the page heading instead of
-- "Search results for...".
function M.buildSearchEpub(epub_path, query, lang, results, callback, custom_title)
    local mtime = os.time()

    local display_title = custom_title or query
    local is_search = not custom_title

    local html_parts = {}
    table.insert(html_parts, '<?xml version="1.0" encoding="utf-8"?>\n')
    table.insert(html_parts, '<!DOCTYPE html>\n')
    table.insert(html_parts, '<html xmlns="http://www.w3.org/1999/xhtml">\n')
    table.insert(html_parts, '<head>\n')
    table.insert(html_parts, '<meta charset="utf-8"/>\n')
    table.insert(html_parts, '<link rel="stylesheet" type="text/css" href="stylesheet.css"/>\n')
    table.insert(html_parts, '<title>')
    if is_search then
        table.insert(html_parts, string.format('Search results for "%s"', query))
    else
        table.insert(html_parts, display_title)
    end
    table.insert(html_parts, '</title>\n')
    table.insert(html_parts, '</head>\n')
    table.insert(html_parts, '<body>\n')
    if is_search then
        table.insert(html_parts, '<h1 class="koreaderwikifrontpage">Search results</h1>\n')
        table.insert(html_parts, '<p class="koreaderwikifrontpage">')
        table.insert(html_parts, string.format('for "%s"', query))
        table.insert(html_parts, '</p>\n')
        table.insert(html_parts, '<hr class="koreaderwikifrontpage"/>\n')
    else
        table.insert(html_parts, '<h1 class="koreaderwikifrontpage">')
        table.insert(html_parts, display_title)
        table.insert(html_parts, '</h1>\n')
        table.insert(html_parts, '<hr class="koreaderwikifrontpage"/>\n')
    end

    for _, result in ipairs(results) do
        local result_title = result.title
        local snippet = (result.snippet or ""):gsub("<[^>]*>", "")
        snippet = util.htmlEntitiesToUtf8(snippet)
        if snippet ~= "" and not snippet:match("[.!?…]$") then
            snippet = snippet .. "…"
        end
        result_title = result_title:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
        snippet = snippet:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
        local link = string.format('https://%s.wikipedia.org/wiki/%s', lang, socket_url.escape(result.title))

        if snippet == "" then
            table.insert(html_parts, string.format(
                '<p class="article-link"><a href="%s">· %s</a></p>\n',
                link, result_title))
        else
            table.insert(html_parts, string.format(
                '<p class="article-link"><a href="%s">· %s</a></p>\n<p class="snippet">%s</p>\n',
                link, result_title, snippet))
        end
    end

    table.insert(html_parts, '</body>\n')
    table.insert(html_parts, '</html>\n')
    local html_content = table.concat(html_parts)

    local css = [[
body {
  text-align: justify;
}
h1.koreaderwikifrontpage {
  text-align: center;
  margin-top: 0;
}
p.koreaderwikifrontpage {
  font-style: italic;
  text-align: center;
  margin-bottom: 1em;
  text-indent: 0;
}
hr.koreaderwikifrontpage {
  margin-left: 20%;
  margin-right: 20%;
  margin-bottom: 1.2em;
}
.search-result {
  margin-bottom: 1em;
}
p.article-link {
  margin: 0.4em 0;
}
p.snippet {
  margin: 0 0 0.8em 0;
  font-size: 80%;
}
a {
  text-decoration: underline;
  color: inherit;
}
]]

    local epub = Archiver.Writer:new{}
    local epub_path_tmp = epub_path .. ".tmp"
    if not epub:open(epub_path_tmp, "epub") then
        callback(false)
        return
    end

    epub:setZipCompression("store")
    epub:addFileFromMemory("mimetype", "application/epub+zip", mtime)
    epub:setZipCompression("deflate")

    epub:addFileFromMemory("META-INF/container.xml", [[
<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>]], mtime)

    local bookid = string.format("search_%s_%s_%d", lang, query:gsub("[^%w]", "_"), mtime)
    local opf = string.format([[
<?xml version='1.0' encoding='utf-8'?>
<package xmlns="http://www.idpf.org/2007/opf"
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        unique-identifier="bookid" version="2.0">
  <metadata>
    <dc:title>Search results for "%s"</dc:title>
    <dc:identifier id="bookid">%s</dc:identifier>
    <dc:language>%s</dc:language>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="content" href="content.html" media-type="application/xhtml+xml"/>
    <item id="css" href="stylesheet.css" media-type="text/css"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="content"/>
  </spine>
</package>
]], query, bookid, lang)
    epub:addFileFromMemory("OEBPS/content.opf", opf, mtime)
    epub:addFileFromMemory("OEBPS/content.html", html_content, mtime)
    epub:addFileFromMemory("OEBPS/stylesheet.css", css, mtime)

    local ncx = string.format([[
<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="%s"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle>
    <text>Search results for "%s"</text>
  </docTitle>
  <navMap>
    <navPoint id="navpoint-1" playOrder="1">
      <navLabel>
        <text>Search results</text>
      </navLabel>
      <content src="content.html"/>
    </navPoint>
  </navMap>
</ncx>
]], bookid, query)
    epub:addFileFromMemory("OEBPS/toc.ncx", ncx, mtime)
    epub:close()

    os.rename(epub_path_tmp, epub_path)
    callback(true, epub_path)
end

--[[-------------------------------------------------------------------------
Category EPUB builder
--]]

-- Build an EPUB for a level of the category tree (subcategories plus any
-- leaf articles), then open it. Subcategories use a special URL format
-- that the link handler intercepts; articles use standard Wikipedia URLs.
function M.buildCategoryEpub(nodes, title, lang, direct_articles)
    local html_parts = {}
    table.insert(html_parts, '<?xml version="1.0" encoding="utf-8"?>\n')
    table.insert(html_parts, '<!DOCTYPE html>\n')
    table.insert(html_parts, '<html xmlns="http://www.w3.org/1999/xhtml">\n')
    table.insert(html_parts, '<head>\n')
    table.insert(html_parts, '<meta charset="utf-8"/>\n')
    table.insert(html_parts, '<link rel="stylesheet" type="text/css" href="stylesheet.css"/>\n')
    table.insert(html_parts, '<title>')
    table.insert(html_parts, title)
    table.insert(html_parts, '</title>\n')
    table.insert(html_parts, '</head>\n')
    table.insert(html_parts, '<body>\n')
    table.insert(html_parts, '<h1>')
    table.insert(html_parts, title)
    table.insert(html_parts, '</h1>\n')
    table.insert(html_parts, '<hr/>\n')

    -- Subcategories
    for _, node in ipairs(nodes) do
        local escaped_title = node.title:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
        local link = string.format('https://%s.wikipedia.org/wiki/Wikipedia:Featured_articles#section_%s',
            lang, node.section_index)
        table.insert(html_parts, string.format(
            '<p class="category-link"><a href="%s">▸ %s</a></p>\n',
            link, escaped_title))
    end

    -- Direct articles
    if direct_articles and #direct_articles > 0 then
        if #nodes > 0 then
            table.insert(html_parts, '<hr/>\n')
        end
        for _, article in ipairs(direct_articles) do
            local escaped_title = article.title:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;")
            local link = string.format('https://%s.wikipedia.org/wiki/%s', lang, socket_url.escape(article.title))
            table.insert(html_parts, string.format(
                '<p class="article-link"><a href="%s">· %s</a></p>\n',
                link, escaped_title))
        end
    end

    table.insert(html_parts, '</body>\n')
    table.insert(html_parts, '</html>\n')
    local html_content = table.concat(html_parts)

    local css = [[
body {
  text-align: justify;
}
h1 {
  text-align: center;
  margin-top: 0;
}
h2 {
  font-size: 120%;
  margin-top: 1em;
}
hr {
  margin-left: 20%;
  margin-right: 20%;
  margin-bottom: 1em;
}
p.category-link {
  margin: 0.5em 0;
}
p.article-link {
  margin: 0.3em 0;
}
a {
  text-decoration: underline;
  color: inherit;
}
]]

    local epub_path = cache.getCachePath("__category__" .. title, lang)
    local mtime = os.time()
    local epub = Archiver.Writer:new{}
    local epub_path_tmp = epub_path .. ".tmp"
    if not epub:open(epub_path_tmp, "epub") then
        return false
    end

    epub:setZipCompression("store")
    epub:addFileFromMemory("mimetype", "application/epub+zip", mtime)
    epub:setZipCompression("deflate")

    epub:addFileFromMemory("META-INF/container.xml", [[
<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>]], mtime)

    local safe_title = title:gsub("[^%w]", "_")
    local bookid = string.format("category_%s_%s_%d", lang, safe_title, mtime)
    local opf = string.format([[
<?xml version='1.0' encoding='utf-8'?>
<package xmlns="http://www.idpf.org/2007/opf"
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        unique-identifier="bookid" version="2.0">
  <metadata>
    <dc:title>%s</dc:title>
    <dc:identifier id="bookid">%s</dc:identifier>
    <dc:language>%s</dc:language>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="content" href="content.html" media-type="application/xhtml+xml"/>
    <item id="css" href="stylesheet.css" media-type="text/css"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="content"/>
  </spine>
</package>
]], title, bookid, lang)
    epub:addFileFromMemory("OEBPS/content.opf", opf, mtime)
    epub:addFileFromMemory("OEBPS/content.html", html_content, mtime)
    epub:addFileFromMemory("OEBPS/stylesheet.css", css, mtime)

    local ncx = string.format([[
<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="%s"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle>
    <text>%s</text>
  </docTitle>
  <navMap>
    <navPoint id="navpoint-1" playOrder="1">
      <navLabel>
        <text>%s</text>
      </navLabel>
      <content src="content.html"/>
    </navPoint>
  </navMap>
</ncx>
]], bookid, title, title)
    epub:addFileFromMemory("OEBPS/toc.ncx", ncx, mtime)
    epub:close()

    os.rename(epub_path_tmp, epub_path)
    return true, epub_path
end

return M
